
nintendo_licensee_codes = {
	'01': 'Nintendo',
	'08': 'Capcom',
	'0A': 'Jaleco',
	'0B': 'Coconuts Japan',
	'13': 'EA Japan',
	'18': 'Hudson Soft',
	'1F': 'Virgin Japan',
	'1M': 'Micro Cabin',
	'1Q': 'TDK (Japan)',
	'20': 'Destination Software',
	'29': 'Seta',
	'2L': 'Tamsoft',
	'2N': 'Smilesoft',
	'2P': 'The Pokémon Company',
	'30': 'Viacom',
	'36': 'Codemasters',
	'39': 'Event Evolution Entertainment',
	'41': 'Ubisoft',
	'46': 'System 3',
	'49': 'Irem',
	'4B': 'Raya Systems',
	'4F': 'U.S. Gold / Eidos',
	'4S': 'Black Pearl Software',
	'4Y': 'Rare',
	'4Z': 'Crave Entertainment',
	'50': 'Absolute Entertainment',
	'51': 'Acclaim',
	'52': 'Activision',
	'55': 'Hi-Tech Expressions',
	'56': 'LJN',
	'58': 'Mattel',
	'5A': 'Mindscape',
	'5D': 'Midway/Tradewest/Williams',
	'5F': 'American Softworks',
	'5G': 'Majesco',
	'5H': 'The 3DO Company',
	'5K': 'Hasbro',
	'5L': 'NewKidsCo',
	'5T': 'Cryo Interactive',
	'5X': 'Microids',
	'60': 'Titus',
	'61': 'Virgin',
	'64': 'LucasArts',
	'67': 'Ocean',
	'69': 'Electronic Arts',
	'6B': 'Laser Beam Entertainment',
	'6F': 'Electro Brain',
	'6H': 'BBC Multimedia',
	'6J': 'Software 2000',
	'6L': 'BAM! Entertainment',
	'6M': 'System 3',
	'6S': 'TDK',
	'6V': 'JoWooD Entertainment',
	'71': 'Interplay',
	'72': 'JVC',
	'75': 'The Sales Curve',
	'78': 'THQ',
	'79': 'Accolade',
	'7F': 'Kemco',
	'7G': 'Rage Software',
	'7J': 'Zoo Digital Publishing',
	'7L': 'Simon & Schuster',
	'82': 'Namcot',
	'8B': 'Bullet-Proof Software',
	'8E': 'Character Soft',
	'8F': "I'Max",
	'8P': 'Sega',
	'93': 'Bec',
	'95': 'Varie',
	'97': 'Kaneko',
	'99': 'Pack-in Video/Victor Interactive/Marvelous Interactive',
	'9A': 'Nichibutsu',
	'9B': 'Tecmo',
	'9C': 'Imagineer',
	'9H': 'Bottom Up',
	'9M': 'Jaguar',
	'9N': 'Marvelous Entertainment',
	'A0': 'Telenet',
	'A4': 'Konami',
	'A5': 'K Amusement Leasing',
	'A7': 'Takara',
	'A8': 'Royal Industries',
	'AD': 'Toho',
	'AF': '[Bandai] Namco',
	'AH': 'J-Wing',
	'AL': 'Media Factory',
	'B0': 'Acclaim Japan',
	'B1': 'ASCII',
	'B2': 'Bandai',
	'B3': 'Soft Pro',
	'B4': 'Enix',
	'B6': 'HAL',
	'BA': 'Culture Brain',
	'BB': 'Sunsoft',
	'BC': 'Toshiba EMI',
	'BD': 'Sony Imagesoft',
	'BJ': 'Compile',
	'BL': 'MTO',
	'C0': 'Taito',
	'C1': 'Sunsoft (Chinou Game Series)',
	'C3': 'Squaresoft',
	'C5': 'Data East',
	'C6': 'Tonkin House',
	'C8': 'Koei',
	'CB': 'Vap',
	'CF': 'Angel',
	'CP': 'Enterbrain',
	'D1': 'SOFEL',
	'D9': 'Banpresto',
	'DA': 'Tomy',
	'DD': 'Masaya',
	'DE': 'Human',
	'DF': 'Altron',
	'E2': 'Yuutaka',
	'E4': 'T&E Soft',
	'E5': 'Epoch',
	'E7': 'Athena',
	'E9': 'Natsume',
	'EB': 'Atlus',
	'FJ': 'Virtual Toys',
	'FQ': 'iQue',
	'FR': 'Digital Tainment Pool',
	'FT': 'Daiwon C&A Holdings',
	'GD': 'Square Enix',
	'GL': 'Gameloft',
	'HF': 'Level5',
	'JS': 'Digital Leisure',
	'KR': 'Krea Medie',
	'KM': 'Deep Silver',
	'RW': 'RealNetworks',
	'WY': 'WayForward',
	'XN': 'Netflix',

	#hmmmmmmmm
	'4Q': 'Disney',
	'54': 'Take-Two Interactive',
	'5Z': 'Classified Games',
	'70': 'Infogrames/Atari, SA',
	'7D': 'Vivendi/Sierra',
	'CE': 'Pony Canyon/FCI',

	#Relatively unverified
	'AC': 'Toei Animation',
	'CA': 'Konami (Ultra Games)',
	'09': 'Hot-B',
	'19': 'Bandai (B-AI)',
	'1P': 'Creatures',
	'35': 'Hector',
	'47': 'Spectrum Holobyte',
	'4A': 'Gakken',
	'53': 'Sammy (America)',
	'5Q': 'Lego',
	'62': 'Maxis',
	'6E': 'Elite Systems',
	'8C': 'Vic Tokai',
	'8N': 'Success',
	'91': 'Chunsoft',
	'9Z': 'Crunchyroll',
	'A6': 'Kawada',
	'A9': 'Technos Japan',
	'BF': 'Sammy',
	'C7': 'East Cube',
	'CU': 'Marvelous AQL',
	'D4': 'Ask Kodansha',
	'D6': 'Naxat Soft',
	'DB': 'Hiro',
	'E1': 'Towa Chiki',
	'E8': 'Asmik',
	'EA': 'King Records',
	'EC': 'Epic / Sony Records',
	'F3': 'Extreme Entertainment',
	'GN': 'OG International',
	'GY': 'The Game Factory',
	'JT': 'Empty Clip Studios',
	'RG': 'Romino Games',
	'TL': 'Telltale',
	'WB': 'Google',
	'WD': 'Amazon',
	'WR': 'Warner Bros',
	'XB': 'Hulu',
	'YV': 'KnapNok Games',
}
