
nintendo_licensee_codes = {
	'01': 'Nintendo',
	'08': 'Capcom',
	'09': 'Hot-B',
	'0A': 'Jaleco',
	'0B': 'Coconuts',
	'0C': 'Elite Systems',
	'13': 'EA Japan',
	'18': 'Hudson Soft',
	'19': 'Bandai (B-AI)',
	'1A': 'Yanoman',
	'1D': 'Clary',
	'1M': 'Micro Cabin',
	'1Q': 'TDK (Japan)',
	'20': 'Zoo',
	'24': 'PCM Complete',
	'29': 'Seta',
	'2L': 'Tamsoft',
	'2N': 'Smilesoft',
	'2P': 'The Pokémon Company',
	'35': 'Hector',
	'36': 'Codemasters',
	'3E': 'Gremlin',
	'41': 'Ubisoft',
	'44': 'Malibu',
	'47': 'Bullet-Proof Software/Spectrum Holobyte',
	'49': 'Irem',
	'4A': 'Gakken',
	'4B': 'Raya Systems',
	'4F': 'Eidos',
	'4Q': 'Disney',
	'4S': 'Black Pearl Software',
	'4Y': 'Rare',
	'4Z': 'Crave Entertainment',
	'50': 'Absolute',
	'51': 'Acclaim',
	'52': 'Activision',
	'53': 'Sammy (America)',
	'54': 'Take-Two Interactive',
	'55': 'Hi-Tech Expressions',
	'56': 'LJN',
	'57': 'Matchbox',
	'58': 'Mattel',
	'59': 'Milton Bradley',
	'5A': 'Mindscape',
	'5B': 'Romstar',
	'5D': 'Midway/Tradewest/Williams',
	'5F': 'American Softworks',
	'5G': 'Majesco',
	'5H': 'The 3DO Company',
	'5K': 'Hasbro',
	'5L': 'NewKidsCo',
	'5Q': 'Lego',
	'5T': 'Cyro Interactive',
	'5X': 'Microids',
	'5Z': 'Classified Games',
	'60': 'Titus',
	'61': 'Virgin',
	'64': 'LucasArts',
	'67': 'Ocean',
	'69': 'Electronic Arts',
	'6B': 'Beam Software/Melbourne House',
	'6F': 'Electro Brain',
	'6H': 'BBC Multimedia',
	'6J': 'Software 2000',
	'6L': 'BAM! Entertainment',
	'6S': 'TDK',
	'6V': 'JoWooD Entertainment',
	'70': 'Infogrames/Atari, SA',
	'71': 'Interplay',
	'72': 'JVC',
	'78': 'THQ',
	'79': 'Accolade',
	'7A': 'Triffix Entertainment',
	'7C': 'Microprose',
	'7D': 'Vivendi',
	'7F': 'Kemco',
	'7G': 'Rage Software',
	'7L': 'Simon & Schuster',
	'80': 'Misawa Entertainment',
	'82': 'Namcot',
	'83': 'LOZC',
	'86': 'Tokuma Shoten',
	'87': 'Tsukuda Ori',
	'8B': 'Bullet-Proof Software',
	'8C': 'Vic Tokai',
	'8E': 'Character Soft',
	'8F': "I'Max",
	'8N': 'Success',
	'8P': 'Sega',
	'91': 'Chunsoft',
	'92': 'Video System',
	'95': 'Varie',
	'97': 'Kaneko',
	'99': 'Pack-in Video/Victor Interactive/Marvelous Interactive',
	'9A': 'Nihon Bussan (Nichibutsu)',
	'9B': 'Tecmo',
	'9C': 'Imagineer',
	'9F': 'Nova',
	'9H': 'Bottom Up',
	'9M': 'Jaguar',
	'9N': 'Marvelous',
	'A0': 'Telenet',
	'A1': 'Hori Electric',
	'A2': 'Scorpion Soft',
	'A4': 'Konami',
	'A5': 'K Amusement Leasing',
	'A6': 'Kawada',
	'A7': 'Takara',
	'A8': 'Royal Industries',
	'A9': 'Technos Japan',
	'AA': 'Broderbund',
	'AC': 'Toei Animation',
	'AD': 'Toho',
	'AF': '[Bandai] Namco',
	'AH': 'J-Wing',
	'AL': 'Media Factory',
	'B1': 'ASCII/Nexoft',
	'B2': 'Bandai',
	'B3': 'Soft Pro',
	'B4': 'Enix',
	'B6': 'HAL',
	'B7': 'SNK',
	'B9': 'Pony Canyon',
	'BA': 'Culture Brain',
	'BB': 'Sunsoft',
	'BC': 'Toshiba EMI',
	'BD': 'Sony Imagesoft',
	'BF': 'Sammy',
	'BJ': 'Compile',
	'BL': 'MTO',
	'C0': 'Taito',
	'C1': 'Sunsoft (Chinou Game Series)',
	'C3': 'Squaresoft',
	'C5': 'Data East',
	'C6': 'Tokyo Shoseki (Tonkin House)',
	'C8': 'Koei',
	'C9': 'UFL',
	'CA': 'Konami (Ultra Games)',
	'CB': 'Vap',
	'CC': 'Use',
	'CD': 'Meldac',
	'CE': 'Pony Canyon',
	'CP': 'Enterbrain',
	'CF': 'Angel',
	'D1': 'SOFEL',
	'D2': 'Bothtec / Quest',
	'D3': 'Sigma Enterprises',
	'D4': 'Ask Kodansha',
	'D6': 'Naxat Soft',
	'D7': 'Copya Systems',
	'D9': 'Banpresto',
	'DA': 'Tomy',
	'DB': 'Hiro',
	'DD': 'Masaka',
	'DE': 'Human',
	'DF': 'Altron',
	'E1': 'Towachiki',
	'E2': 'Yuutaka',
	'E4': 'T&E Soft',
	'E5': 'Epoch',
	'E7': 'Athena',
	'E8': 'Asmik',
	'E9': 'Natsume',
	'EA': 'King Records',
	'EB': 'Atlus',
	'EC': 'Epic/Sony Records',
	'EE': 'Information Global Services',
	'F0': 'A Wave',
	'F3': 'Extreme Entertainment',
	'FJ': 'Virtual Toys',
	'FQ': 'iQue',
	'FR': 'Digital Tainment Pool',
	'FT': 'Daiwon C&A Holdings',
	'GD': 'Square Enix',
	'GL': 'Gameloft',
	'HF': 'Level5',
	'JS': 'Digital Leisure',
	'KM': 'Deep Silver',
	'KR': 'Krea Medie',
	'RW': 'RealNetworks',
	'TL': 'Telltale',
	'WY': 'WayForward',
}
